// Code generated by "stringer --type GameStatus"; DO NOT EDIT.

package tictactoe

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CircleVictory-1]
	_ = x[CrossVictory - -1]
	_ = x[Tie-0]
	_ = x[OnGoing-2]
}

const _GameStatus_name = "CrossVictoryTieCircleVictoryOnGoing"

var _GameStatus_index = [...]uint8{0, 12, 15, 28, 35}

func (i GameStatus) String() string {
	i -= -1
	if i < 0 || i >= GameStatus(len(_GameStatus_index)-1) {
		return "GameStatus(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _GameStatus_name[_GameStatus_index[i]:_GameStatus_index[i+1]]
}
